# FROM openjdk:8-jre-alpine
FROM  alpine:3.8

# copy WAR into image
COPY event-reactive-service-0.0.1-SNAPSHOT.jar /event-reactive.jar
# run application with this command line 
CMD ["/usr/bin/java", "-jar",  "/event-reactive.jar"]

# C:\Users\moez\Documents\workspace-spring-tool-suite-4-4.2.1.RELEASE\event-reactive-service\
# target\event-reactive-service-0.0.1-SNAPSHOT.jar